name: Playwright CI + Allure Pages

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write  # Necesario para publicar en gh-pages

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Clean npm cache (recomendado al cambiar versiones)
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci
        env:
          NODE_ENV: development  # Asegura que se instalen devDependencies

      - name: Debug dependencies
        run: ls -la node_modules/@cucumber

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Cucumber tests
        run: |
          npx cucumber-js features/**/*.feature \
            --require features/step_definitions/**/*.ts \
            --require-module ts-node/register \
            --format progress

      - name: Install Allure CLI globally
        run: npm install -g allure-commandline

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean
          ls -la allure-report/

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
